// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hpxjbrimooseniaeuelk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhweGpicmltb29zZW5pYWV1ZWxrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5ODg3MTMsImV4cCI6MjA2ODU2NDcxM30.Uul4cAcjKsJKUd5ug2v6_7t-Z45VeM3JPf87UFNZAZ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});